In [0]:
import pandas as pd
import numpy as np

In [39]:
# from google.colab import files

# uploaded = files.upload()

In [0]:
data = pd.read_csv('pima-indians-diabetes.csv')

In [41]:
data

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
5     3   78  50  32   88  31.0  0.248  26  1
6    10  115   0   0    0  35.3  0.134  29  0
7     2  197  70  45  543  30.5  0.158  53  1
8     8  125  96   0    0   0.0  0.232  54  1
9     4  110  92   0    0  37.6  0.191  30  0
10   10  168  74   0    0  38.0  0.537  34  1
11   10  139  80   0    0  27.1  1.441  57  0
12    1  189  60  23  846  30.1  0.398  59  1
13    5  166  72  19  175  25.8  0.587  51  1
14    7  100   0   0    0  30.0  0.484  32  1
15    0  118  84  47  230  45.8  0.551  31  1
16    7  107  74   0    0  29.6  0.254  31  1
17    1  103  30  38   83  43.3  0.183  33  0
18    1  115  70  30   96  34.6  0.529  32  1
19    3  126  88  41  235  39.3  0.704  27  0
20    8   99  84   0    0  35.4  0.388  50  0
21    7  196  90   0    0  39.8  0.451  41  1
22    9  119  80  35    0  29.0  0.263  29  1
23   11  143  94  33  146  36.6  0.254  51  1
24   10  125  70  26  115  31.1  0.205  41  1
25    7  147  76   0    0  39.4  0.257  43  1
26    1   97  66  15  140  23.2  0.487  22  0
27   13  145  82  19  110  22.2  0.245  57  0
28    5  117  92   0    0  34.1  0.337  38  0
29    5  109  75  26    0  36.0  0.546  60  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
737   2   99  60  17  160  36.6  0.453  21  0
738   1  102  74   0    0  39.5  0.293  42  1
739  11  120  80  37  150  42.3  0.785  48  1
740   3  102  44  20   94  30.8  0.400  26  0
741   1  109  58  18  116  28.5  0.219  22  0
742   9  140  94   0    0  32.7  0.734  45  1
743  13  153  88  37  140  40.6  1.174  39  0
744  12  100  84  33  105  30.0  0.488  46  0
745   1  147  94  41    0  49.3  0.358  27  1
746   1   81  74  41   57  46.3  1.096  32  0
747   3  187  70  22  200  36.4  0.408  36  1
748   6  162  62   0    0  24.3  0.178  50  1
749   4  136  70   0    0  31.2  1.182  22  1
750   1  121  78  39   74  39.0  0.261  28  0
751   3  108  62  24    0  26.0  0.223  25  0
752   0  181  88  44  510  43.3  0.222  26  1
753   8  154  78  32    0  32.4  0.443  45  1
754   1  128  88  39  110  36.5  1.057  37  1
755   7  137  90  41    0  32.0  0.391  39  0
756   0  123  72   0    0  36.3  0.258  52  1
757   1  106  76   0    0  37.5  0.197  26  0
758   6  190  92   0    0  35.5  0.278  66  1
759   2   88  58  26   16  28.4  0.766  22  0
760   9  170  74  31    0  44.0  0.403  43  1
761   9   89  62   0    0  22.5  0.142  33  0
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [42]:
data = data.values
data

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 1.67e-01, 2.10e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [43]:
x = data[:,0:8].astype(float)

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
print(x_scaled)

x_train = x_scaled[0:540]
x_test = x_scaled[541:760]

[[0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 [0.05882353 0.44723618 0.54098361 ... 0.41877794 0.03800171 0.        ]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [44]:
y = data[:,8]
print(y)
y_train = y[0:540]
y_test = y[541:760]

[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1.
 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0.

In [45]:
len(x_train)

540

In [46]:
len(x_test)

219

In [0]:
from keras import models
from keras import layers

In [0]:
network = models.Sequential()
network.add(layers.Dense(12, activation='relu', input_dim=8))
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(8, activation='relu'))
network.add(layers.Dense(4, activation='relu'))
network.add(layers.Dense(1, activation='sigmoid'))

In [0]:
network.compile(optimizer='rmsprop',
                loss='binary_crossentropy',
                metrics=['accuracy'])

In [50]:
network.fit(x_train, y_train, validation_split=0.3, shuffle=True, epochs=70, batch_size=10)

Train on 378 samples, validate on 162 samples
Epoch 1/70
378/378 [==============================] - 0s 1ms/step - loss: 0.6900 - acc: 0.5556 - val_loss: 0.6804 - val_acc: 0.6790
Epoch 2/70
378/378 [==============================] - 0s 601us/step - loss: 0.6731 - acc: 0.6720 - val_loss: 0.6570 - val_acc: 0.7160
Epoch 3/70
378/378 [==============================] - 0s 600us/step - loss: 0.6600 - acc: 0.6534 - val_loss: 0.6407 - val_acc: 0.7284
Epoch 4/70
378/378 [==============================] - 0s 600us/step - loss: 0.6483 - acc: 0.6825 - val_loss: 0.6235 - val_acc: 0.7284
Epoch 5/70
378/378 [==============================] - 0s 621us/step - loss: 0.6376 - acc: 0.6640 - val_loss: 0.6120 - val_acc: 0.7346
Epoch 6/70
378/378 [==============================] - 0s 607us/step - loss: 0.6266 - acc: 0.6958 - val_loss: 0.5966 - val_acc: 0.7222
Epoch 7/70
378/378 [==============================] - 0s 612us/step - loss: 0.6169 - acc: 0.6984 - val_loss: 0.5867 - val_acc: 0.7346
Epoch 8/70
378/378

378/378 [==============================] - 0s 701us/step - loss: 0.5604 - acc: 0.7169 - val_loss: 0.5389 - val_acc: 0.7469
Epoch 17/70
378/378 [==============================] - 0s 701us/step - loss: 0.5544 - acc: 0.7143 - val_loss: 0.5472 - val_acc: 0.7407
Epoch 18/70
378/378 [==============================] - 0s 713us/step - loss: 0.5524 - acc: 0.7143 - val_loss: 0.5214 - val_acc: 0.7840
Epoch 19/70
378/378 [==============================] - 0s 721us/step - loss: 0.5509 - acc: 0.7169 - val_loss: 0.5185 - val_acc: 0.7840
Epoch 20/70
378/378 [==============================] - 0s 721us/step - loss: 0.5484 - acc: 0.7143 - val_loss: 0.5190 - val_acc: 0.7654
Epoch 21/70
378/378 [==============================] - 0s 703us/step - loss: 0.5426 - acc: 0.7143 - val_loss: 0.5103 - val_acc: 0.7654
Epoch 22/70
378/378 [==============================] - 0s 734us/step - loss: 0.5425 - acc: 0.7222 - val_loss: 0.5215 - val_acc: 0.7716
Epoch 23/70
378/378 [==============================] - 0s 713us/ste

378/378 [==============================] - 0s 714us/step - loss: 0.5269 - acc: 0.7513 - val_loss: 0.4899 - val_acc: 0.7778
Epoch 32/70
378/378 [==============================] - 0s 721us/step - loss: 0.5194 - acc: 0.7513 - val_loss: 0.4908 - val_acc: 0.7778
Epoch 33/70
378/378 [==============================] - 0s 744us/step - loss: 0.5228 - acc: 0.7328 - val_loss: 0.5064 - val_acc: 0.7778
Epoch 34/70
378/378 [==============================] - 0s 732us/step - loss: 0.5200 - acc: 0.7434 - val_loss: 0.5128 - val_acc: 0.7716
Epoch 35/70
378/378 [==============================] - 0s 710us/step - loss: 0.5205 - acc: 0.7513 - val_loss: 0.5016 - val_acc: 0.7901
Epoch 36/70
378/378 [==============================] - 0s 718us/step - loss: 0.5184 - acc: 0.7460 - val_loss: 0.4989 - val_acc: 0.7963
Epoch 37/70
378/378 [==============================] - 0s 724us/step - loss: 0.5156 - acc: 0.7354 - val_loss: 0.4807 - val_acc: 0.7716
Epoch 38/70
378/378 [==============================] - 0s 704us/ste

378/378 [==============================] - 0s 708us/step - loss: 0.5075 - acc: 0.7540 - val_loss: 0.4854 - val_acc: 0.7901
Epoch 47/70
378/378 [==============================] - 0s 716us/step - loss: 0.5046 - acc: 0.7513 - val_loss: 0.4787 - val_acc: 0.8148
Epoch 48/70
378/378 [==============================] - 0s 734us/step - loss: 0.5059 - acc: 0.7513 - val_loss: 0.4939 - val_acc: 0.7778
Epoch 49/70
378/378 [==============================] - 0s 705us/step - loss: 0.5059 - acc: 0.7460 - val_loss: 0.4841 - val_acc: 0.7840
Epoch 50/70
378/378 [==============================] - 0s 711us/step - loss: 0.5039 - acc: 0.7513 - val_loss: 0.4685 - val_acc: 0.8086
Epoch 51/70
378/378 [==============================] - 0s 722us/step - loss: 0.5006 - acc: 0.7434 - val_loss: 0.4652 - val_acc: 0.7840
Epoch 52/70
378/378 [==============================] - 0s 742us/step - loss: 0.5021 - acc: 0.7593 - val_loss: 0.4630 - val_acc: 0.7963
Epoch 53/70
378/378 [==============================] - 0s 726us/ste

378/378 [==============================] - 0s 737us/step - loss: 0.4942 - acc: 0.7566 - val_loss: 0.4748 - val_acc: 0.8086
Epoch 62/70
378/378 [==============================] - 0s 735us/step - loss: 0.4894 - acc: 0.7725 - val_loss: 0.4709 - val_acc: 0.8086
Epoch 63/70
378/378 [==============================] - 0s 742us/step - loss: 0.4923 - acc: 0.7434 - val_loss: 0.4620 - val_acc: 0.8086
Epoch 64/70
378/378 [==============================] - 0s 729us/step - loss: 0.4950 - acc: 0.7646 - val_loss: 0.4737 - val_acc: 0.8025
Epoch 65/70
378/378 [==============================] - 0s 726us/step - loss: 0.4924 - acc: 0.7513 - val_loss: 0.4599 - val_acc: 0.8148
Epoch 66/70
378/378 [==============================] - 0s 716us/step - loss: 0.4910 - acc: 0.7381 - val_loss: 0.4645 - val_acc: 0.8086
Epoch 67/70
378/378 [==============================] - 0s 734us/step - loss: 0.4878 - acc: 0.7672 - val_loss: 0.4576 - val_acc: 0.8148
Epoch 68/70
378/378 [==============================] - 0s 726us/ste

In [51]:

network.evaluate(x_test, y_test)

219/219 [==============================] - 0s 109us/step


[0.44822071322567386, 0.7899543414377186]

In [53]:
vectors_answers = network.predict(x_test[210:])
vectors_answers = np.where(vectors_answers > 0.5, 1, 0)
print(vectors_answers)

[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]]
